version: 2
updates:
  # Github actions
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Docker compose
  
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Postgres - docker

  - package-ecosystem: "docker"
    directory: "/postgres"
    schedule:
      interval: "weekly"

  # API - docker and npm

  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      api-docker:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      api-npm:
        patterns: ["*"]

  # Frontend - docker and npm

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      frontend-docker:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/frontend/src"
    schedule:
      interval: "weekly"
    groups:
      frontend-npm:
        patterns: ["*"]

  # Worker - docker and gomod

  - package-ecosystem: "docker"
    directory: "/worker"
    schedule:
      interval: "weekly"
    groups:
      worker-docker:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/worker/src"
    schedule:
      interval: "weekly"
    groups:
      worker-go:
        patterns: ["*"]

  # Nginx - docker

  - package-ecosystem: "docker"
    directory: "/infra/nginx"
    schedule:
      interval: "weekly"