FROM node:24-bookworm-slim@sha256:a81a03dd965b4052269a57fac857004022b522a4bf06e7a739e25e18bce45af2

WORKDIR /app

COPY src/package*.json ./
RUN npm install

COPY src .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]