# Stage 1: Build the Vite app
FROM node:25-alpine3@sha256:b9b5737eabd423ba73b21fe2e82332c0656d571daf1ebf19b0f89d0dd0d3ca93 AS builder
WORKDIR /app
COPY frontend/src/package*.json ./
RUN npm ci
COPY frontend/src/ .
RUN npm run build

# Stage 2: Final Nginx Image
FROM nginx:stable-alpine@sha256:0272e4604ed93c1792f03695a033a6e8546840f86e0de20a884bb17d2c924883

# Copy the static files from the builder stage
COPY --from=builder /app/dist /usr/share/nginx/html
# Copy prod config
ARG NGINX_CONFIG=prod
COPY /infra/nginx/${NGINX_CONFIG}.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]