apiVersion: apps/v1
kind: Deployment
metadata:
  name: encoder-model
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encoder-model
  template:
    metadata:
      labels:
        app: encoder-model
    spec:
      containers:
      - name: encoder-model
        image: sgawalsh/video-analysis-encoder-model:latest

        ports:
        - containerPort: 8000

        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"

        startupProbe:
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 60