apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm_worker
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm_worker
  template:
    metadata:
      labels:
        app: llm_worker
    spec:
      containers:
        - name: llm_worker
          image: sgawalsh/video-analysis-worker:latest
          ports:
            - name: metrics
              containerPort: 2112
          env:
            - name: role
              value: llm_worker
            - name: llm_concurrency
              value: "1"
          envFrom:
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: llm-worker-config
            - secretRef:
                name: postgres-secret
